export const NOTIFICATIONS_TAB_ON = "NOTIFICATIONS_TAB_ON";
export const NOTIFICATIONS_TAB_OFF = "NOTIFICATIONS_TAB_OFF";
export const NOTIFICATIONS_UPDATE = "NOTIFICATIONS_UPDATE";
export const NOTIFICATIONS_PAG_PAGE_SET = "NOTIFICATIONS_PAG_PAGE_SET";

// LANDING
export const PERSIST = "PERSIST";
export const TOGGLE_LR = "TOGGLE_LR";
export const TOGGLE_REMEMBER_ME = "TOGGLE_REMEMBER_ME";
export const SET_USER_INPUT = "SET_USER_INPUT";
export const USER_INPUTS_CLEAR = "USER_INPUTS_CLEAR";
export const MESSAGE_CLEAR = "MESSAGE_CLEAR";
export const SET_MSG_INPUT = "SET_MSG_INPUT";
export const TOGGLE_FOCUSED = "TOGGLE_FOCUSED";
export const CAN_ANIMATE_PSW2 = "CAN_ANIMATE_PSW2";

// POST
export const SET_POSTS = "SET_POSTS";
export const SORT_POSTS = "SORT_POSTS";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";
export const RESET_POSTS = "RESET_POSTS";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const SEND_COMMENT = "SEND_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

// CHAT
export const ADD_TARGET = "ADD_TARGET";
export const REMOVE_TARGET = "REMOVE_TARGET";
export const REMOVE_TARGET_ALL = "REMOVE_TARGET_ALL";
export const SET_ONLY_ONE_TARGET_ID0 = "SET_ONLY_ONE_TARGET_ID0";
export const SET_MESSAGE_INPUT = "SET_MESSAGE_INPUT";
export const UPDATE_MESSAGES = "UPDATE_MESSAGES";
export const CHAT_WINDOW_STATE = "CHAT_WINDOW_STATE";
export const SET_CAN_SCROLL = "SET_CAN_SCROLL";
export const SET_IS_TYPING = "SET_IS_TYPING";
export const SET_NTF_OPEN = "SET_NTF_OPEN";
export const SET_NTF_DATA = "SET_NTF_DATA";
export const DEL_ALL_NOTIFICATIONS = "DEL_ALL_NOTIFICATIONS";
