export const NOTIFICATIONS_TAB_ON = "NOTIFICATIONS_TAB_ON";
export const NOTIFICATIONS_TAB_OFF = "NOTIFICATIONS_TAB_OFF";
export const NOTIFICATIONS_UPDATE = "NOTIFICATIONS_UPDATE";
export const NOTIFICATIONS_PAG_PAGE_SET = "NOTIFICATIONS_PAG_PAGE_SET";

// LANDING
export const PERSIST = "PERSIST";
export const TOGGLE_LR = "TOGGLE_LR";
export const TOGGLE_REMEMBER_ME = "TOGGLE_REMEMBER_ME";
export const SET_USER_INPUT = "SET_USER_INPUT";
export const TOGGLE_FOCUSED = "TOGGLE_FOCUSED";
export const CAN_ANIMATE_PSW2 = "CAN_ANIMATE_PSW2";
