export const NOTIFICATIONS_TAB_ON = "NOTIFICATIONS_TAB_ON";
export const NOTIFICATIONS_TAB_OFF = "NOTIFICATIONS_TAB_OFF";
export const NOTIFICATIONS_UPDATE = "NOTIFICATIONS_UPDATE";
export const NOTIFICATIONS_PAG_PAGE_SET = "NOTIFICATIONS_PAG_PAGE_SET";
